### ISSUE TITLE
Testing "private" repositories

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#106]
A repository is private if its `public_access` attribute is set to `None`. If a repository is private, then its content should not be available in the global search and only users with appropriate permissions should be able to view it directly. There are a number of scenarios to test.

Given (I have an import script for DemoOrg):
* Organization: DemoOrg
* Source: DemoSource, containing concepts and mappings, with initial empty repo version and v1.0
* Collection: DemoCollection, containing references to concepts/mappings in DemoSource, with initial empty version and v1.0

Public Access Options:

Resource | Attribute | Values
-- | -- | --
DemoOrg | public_access | None, View, Edit
DemoSource | public_access | None, View, Edit
DemoCollection | public_access | None, View, Edit

Users:
* Anonymous
* Authenticated, not a member of org
* Authenticated org member
* Superuser

Test Scenarios:
* Highest priority:
    * public_access set to None for DemoOrg/Source/Collection
* Comprehensive approach:
    * Test all combinations of the above: (3^3 public access combinations) * (4 types of users) = (108 possible combinations)
    * Test *changing* public_access (e.g. from `None` to `View`, or vice versa) after content has been created and indexed

Test CRUD for the following (there are definitely more!):
@rkorytkowski: I'm crossing out fully tested endpoints (CRUD by anonymous, member, nonmember and staff)
* Resources
    * ~~/orgs/DemoOrg/~~
    * /orgs/DemoOrg/members/
    * ~~/orgs/DemoOrg/sources/~~
    * ~~/orgs/DemoOrg/sources/DemoSource/~~
    * /orgs/DemoOrg/sources/DemoSource/versions/
    * /orgs/DemoOrg/sources/DemoSource/initial/
    * /orgs/DemoOrg/sources/DemoSource/v1.0/
    * /orgs/DemoOrg/sources/DemoSource/concepts/ (tested list only)
    * /orgs/DemoOrg/sources/DemoSource/mappings/ (tested list only)
    * /orgs/DemoOrg/sources/DemoSource/concepts/Food/
    * /orgs/DemoOrg/sources/DemoSource/mappings/.../
    * ~~/orgs/DemoOrg/collections/~~
    * ~~/orgs/DemoOrg/collections/DemoCollection/~~
    * /orgs/DemoOrg/collections/DemoCollection/versions/
    * /orgs/DemoOrg/collections/DemoCollection/initial/
    * /orgs/DemoOrg/collections/DemoCollection/v1.0/
    * /orgs/DemoOrg/collections/DemoCollection/concepts/ (tested read only)
    * /orgs/DemoOrg/collections/DemoCollection/mappings/ (tested read only)
    * /orgs/DemoOrg/collections/DemoCollection/references/
    * /orgs/DemoOrg/collections/DemoCollection/concepts/Food/
    * /orgs/DemoOrg/collections/DemoCollection/mappings/.../
* Global search
    * /concepts/ (tested read only)
    * /mappings/ (tested read only)
    * ~~/sources/~~
    * ~~/collections/~~
    * ~~/orgs/~~

**Comment by paynejd** [comment]
@rkorytkowski We are planning to host some of PEPFAR's content as private (ie. setting `public_access` to `None` for the org and its sources/collections). During my initial testing, it appears that a `public_access` setting of `None` is not always handled properly, meaning that users who are not a member of the org may still have access. However, we do not currently have a way to test this. Rather than do it manually, it seems like this would be best as a test script that is incorporated into the deployment process.

What's the best way to go about doing this?

**Comment by dtreatman** [comment]
Just noting that we came across this issue in testing today as well. We found that an Authenticated user was able to access a source with a public_access setting of None, either by navigating to the source URL (https://openconceptlab.org/users/dtreatman/sources/Canada-test/) or by clicking on the source from the list of user sources (https://openconceptlab.org/users/dtreatman/). Happy support testing once a fix is deployed.

**Comment by paynejd** [comment]
Thanks @dtreatman for reporting this! We've tested this to the point that we know setting a repository to private does not incorrectly block access to a user that should have access -- meaning you can safely set an org or repo's "public_access" to "None" and you'll still have access to your content. There are several endpoints though where users that should not have access will still be able to access it.

**Comment by paynejd** [comment]
FYI work on this ended up happening in #102 -- a change was made that now better enforces the privacy setting, but it resulted in operations from the OCL web application being incorrectly performed by the root user rather than by the requesting user. If you make the request from the API directly using your token, it is performed by the correct user. This is a top priority issue so we'll have our developer working on this ASAP.

**Comment by paynejd** [comment]
If an org has "public_access" set to "View", an anonymous user should be able to view the org's details, and list of repositories. For example, this page should not be blocked: https://openconceptlab.org/orgs/OCL/

Note: the concept page is working correctly: https://openconceptlab.org/orgs/OCL/sources/NameTypes/concepts/

**Comment by paynejd** [comment]
Also, note that the search page has zero orgs results, probably due to the same issue: https://openconceptlab.org/search/

**Comment by rkorytkowski** [comment]
@paynejd, thanks for testing. I've addressed the orgs issue. It's being deployed to QA. I'll push it to other envs on Monday.

**Comment by rkorytkowski** [comment]
I'll work on tests now...

**Comment by rkorytkowski** [comment]
As part of this issue I'm going to introduce a new API test setup based on Postman. API tests will be written in Javascript. We will be able to run them against any server so that we can use them for builds, but also post deployments verification of qa, staging, demo and production envs.

We will be deprecating our old Django API integration tests in favor of Postman tests, which are easier to write and maintain.

**Comment by paynejd** [comment]
Awesome -- that sounds like a great approach, and helps us to be less tied
to our old version of django!

**Comment by rkorytkowski** [comment]
Finally decided not to use Postman rather Jest. Jest is a testing framework of choice for React devs. Tests are super easy to write, run and debug. One just needs a text editor to write them as opposed to Postman.

Added simple login tests in https://github.com/OpenConceptLab/oclapi/commit/9f364f83ab6504b740ac59f5bcbd60bf924c2fc3 

Included in CI build.

I'll add a config to run some of them on qa, staging and production environments.

**Comment by paynejd** [comment]
Please refer to urgent email just now with subject "URGENT: OCL Production having issues importing mappings from DATIM"

**Comment by rkorytkowski** [comment]
Partially completed. Moving to backlog for now...
