### ISSUE TITLE
Permissions Issue: Concepts appear in Global Search but the Source is restricted

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#779]
A source in QA has been set to Private i.e. `public_access=None`, but when I anonymously do a global search for "ihtsdo", concepts from that source still appear in the search. Since the source is private, its concepts should not appear in global search for anonymous users or users without the proper permissions.

https://app.qa.openconceptlab.org/#/orgs/International-Health-Terminology-Standard-Development-Organisation-IHTSDO-/sources/SNOMED/

@snyaggarwal Can you take a look into this and see why it is behaving this way?

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed and deployed

**Comment by snyaggarwal** [comment]
@paynejd this should be fixed now

**Comment by jamlung-ri** [comment]
This is looking good to me now! @paynejd Please feel free to close this out if you are seeing the expected behavior. I'll close out this ticket in a couple days if I don't see any activity.

**Comment by jamlung-ri** [comment]
@snyaggarwal It seems like this issue has come back up again, at least in QA. Not sure what happened, but the restricted source ([link to SNOMED](https://app.qa.openconceptlab.org/#/orgs/International-Health-Terminology-Standard-Development-Organisation-IHTSDO-/sources/SNOMED/)) is set to Private, but I can still see it when searching IHTSDO anonymously ([link](https://app.qa.openconceptlab.org/#/search/?q=ihtsdo)). The SNOMED source is not appearing in the Source list, but its concepts are still showing.

**Comment by snyaggarwal** [comment]
@jamlung-ri Fixed this. It was missing indexing

**Comment by jamlung-ri** [comment]
Gotcha, I wondered if that had something to do with it. It's now working properly. Thanks!
